add_executable(OneLife)

target_sources(OneLife PRIVATE
	minitech.cpp
	game.cpp
	spriteBank.cpp
	objectBank.cpp
	transitionBank.cpp
	animationBank.cpp
	whiteSprites.cpp
	message.cpp
	serialWebRequests.cpp
	accountHmac.cpp
	PageComponent.cpp
	GamePage.cpp
	LivingLifePage.cpp
	pathFind.cpp
	ageControl.cpp
	ExtendedMessagePage.cpp
	buttonStyle.cpp
	Button.cpp
	TextButton.cpp
	RebirthChoicePage.cpp
	TextField.cpp
	DropdownList.cpp
	LoadingPage.cpp
	folderCache.cpp
	binFolderCache.cpp
	liveObjectSet.cpp
	../commonSource/fractalNoise.cpp
	../commonSource/sayLimit.cpp
	ExistingAccountPage.cpp
	KeyEquivalentTextButton.cpp
	ServerActionPage.cpp
	FinalMessagePage.cpp
	AutoUpdatePage.cpp
	soundBank.cpp
	convolution.cpp
	fft.cpp
	ogg.cpp
	musicPlayer2.cpp
	groundSprites.cpp
	SettingsPage.cpp
	CheckboxButton.cpp
	ValueSlider.cpp
	SpriteButton.cpp
	SpriteToggleButton.cpp
	categoryBank.cpp
	liveAnimationTriggers.cpp
	ReviewPage.cpp
	TextArea.cpp
	RadioButtonSet.cpp
	spellCheck.cpp
	SoundUsage.cpp
	TwinPage.cpp
	objectMetadata.cpp
	emotion.cpp
	Picker.cpp
	PickableStatics.cpp
	photos.cpp
	lifeTokens.cpp
	PollPage.cpp
	fitnessScore.cpp
	GeneticHistoryPage.cpp
)

target_link_libraries(OneLife PRIVATE
	MINOR_GEMS_BASE
	MINOR_GEMS_GRAPHICS_LIBS

	MINOR_GEMS_SCREEN_GL_SDL
	MINOR_GEMS_SINGLE_TEXTURE_GL
	MINOR_GEMS_TYPE_IO
	MINOR_GEMS_STRING_UTILS
	MINOR_GEMS_STRING_BUFFER_OUTPUT_STREAM
	MINOR_GEMS_BYTE_BUFFER_INPUT_STREAM
	MINOR_GEMS_PATH
	MINOR_GEMS_TIME
	MINOR_GEMS_THREAD
	MINOR_GEMS_MUTEX_LOCK
	MINOR_GEMS_BINARY_SEMAPHORE
	MINOR_GEMS_TRANSLATION_MANAGER
	MINOR_GEMS_SOCKET
	MINOR_GEMS_HOST_ADDRESS
	MINOR_GEMS_SOCKET_CLIENT
	MINOR_GEMS_SOCKET_SERVER
	MINOR_GEMS_NETWORK_FUNCTION_LOCKS
	MINOR_GEMS_LOOKUP_THREAD
	MINOR_GEMS_WEB_REQUEST
	MINOR_GEMS_URL_UTILS
	MINOR_GEMS_SETTINGS_MANAGER
	MINOR_GEMS_FINISHED_SIGNAL_THREAD
	MINOR_GEMS_STOP_SIGNAL_THREAD
	MINOR_GEMS_SHA1
	MINOR_GEMS_ENCODING_UTILS
	MINOR_GEMS_DIRECTORY
	MINOR_GEMS_LOG
	MINOR_GEMS_APP_LOG
	MINOR_GEMS_FILE_LOG
	MINOR_GEMS_PRINT_LOG
	MINOR_GEMS_PRINT_UTILS
	MINOR_GEMS_GAME_SDL
	MINOR_GEMS_GAME_GRAPHICS_GL
	MINOR_GEMS_SPRITE_GL
	MINOR_GEMS_DOUBLE_PAIR
	MINOR_GEMS_FONT
	MINOR_GEMS_DRAW_UTILS
	MINOR_GEMS_DEMO_CODE_CHECKER
	MINOR_GEMS_AIFF
	MINOR_GEMS_AUDIO_NO_CLIP
	MINOR_GEMS_SOUND_SAMPLES
	MINOR_GEMS_REVERB_SOUND_FILTER
	MINOR_GEMS_COEFFICIENT_FILTERS
	MINOR_GEMS_CURVE_25519
	MINOR_GEMS_CRYPTO_RANDOM
	MINOR_GEMS_DIFF_BUNDLE_CLIENT
	MINOR_GEMS_STRING_TREE
	MINOR_GEMS_CRC32
)
