add_executable(EditOneLife)

target_sources(EditOneLife PRIVATE
	editor.cpp
	PageComponent.cpp
	GamePage.cpp
	TextField.cpp
	DropdownList.cpp
	Button.cpp
	TextButton.cpp
	whiteSprites.cpp
	serialWebRequests.cpp
	message.cpp
	accountHmac.cpp
	EditorImportPage.cpp
	spriteBank.cpp
	Picker.cpp
	objectBank.cpp
	EditorObjectPage.cpp
	transitionBank.cpp
	EditorTransitionPage.cpp
	SpriteButton.cpp
	SpriteToggleButton.cpp
	CheckboxButton.cpp
	animationBank.cpp
	EditorAnimationPage.cpp
	EditorSpriteTrimPage.cpp
	ValueSlider.cpp
	ageControl.cpp
	overlayBank.cpp
	keyLegend.cpp
	LoadingPage.cpp
	folderCache.cpp
	binFolderCache.cpp
	PickableStatics.cpp
	soundBank.cpp
	SoundWidget.cpp
	convolution.cpp
	fft.cpp
	zoomView.cpp
	categoryBank.cpp
	EditorCategoryPage.cpp
	RadioButtonSet.cpp
	EditorScenePage.cpp
	groundSprites.cpp
	../commonSource/fractalNoise.cpp
	spellCheck.cpp
	SoundUsage.cpp
	objectMetadata.cpp
	emotion.cpp
)

target_link_libraries(EditOneLife PRIVATE
	MINOR_GEMS_LIBPNG

	MINOR_GEMS_BASE
	MINOR_GEMS_GRAPHICS_LIBS

	MINOR_GEMS_SCREEN_GL_SDL
	MINOR_GEMS_SINGLE_TEXTURE_GL
	MINOR_GEMS_TYPE_IO
	MINOR_GEMS_STRING_UTILS
	MINOR_GEMS_STRING_BUFFER_OUTPUT_STREAM
	MINOR_GEMS_BYTE_BUFFER_INPUT_STREAM
	MINOR_GEMS_PATH
	MINOR_GEMS_TIME
	MINOR_GEMS_THREAD
	MINOR_GEMS_MUTEX_LOCK
	MINOR_GEMS_TRANSLATION_MANAGER
	MINOR_GEMS_SOCKET
	MINOR_GEMS_HOST_ADDRESS
	MINOR_GEMS_SOCKET_CLIENT
	MINOR_GEMS_SOCKET_SERVER
	MINOR_GEMS_NETWORK_FUNCTION_LOCKS
	MINOR_GEMS_LOOKUP_THREAD
	MINOR_GEMS_WEB_REQUEST
	MINOR_GEMS_URL_UTILS
	MINOR_GEMS_SETTINGS_MANAGER
	MINOR_GEMS_FINISHED_SIGNAL_THREAD
	MINOR_GEMS_STOP_SIGNAL_THREAD
	MINOR_GEMS_SHA1
	MINOR_GEMS_ENCODING_UTILS
	MINOR_GEMS_DIRECTORY
	MINOR_GEMS_LOG
	MINOR_GEMS_APP_LOG
	MINOR_GEMS_FILE_LOG
	MINOR_GEMS_PRINT_LOG
	MINOR_GEMS_PRINT_UTILS
	MINOR_GEMS_GAME_SDL
	MINOR_GEMS_GAME_GRAPHICS_GL
	MINOR_GEMS_SPRITE_GL
	MINOR_GEMS_DOUBLE_PAIR
	MINOR_GEMS_FONT
	MINOR_GEMS_DRAW_UTILS
	MINOR_GEMS_DEMO_CODE_CHECKER
	MINOR_GEMS_AIFF
	MINOR_GEMS_AUDIO_NO_CLIP
	MINOR_GEMS_SOUND_SAMPLES
	MINOR_GEMS_REVERB_SOUND_FILTER
	MINOR_GEMS_COEFFICIENT_FILTERS
	MINOR_GEMS_CURVE_25519
	MINOR_GEMS_CRYPTO_RANDOM
	MINOR_GEMS_DIFF_BUNDLE_CLIENT
	MINOR_GEMS_STRING_TREE
	MINOR_GEMS_BINARY_SEMAPHORE
)
